export const TERM_DATA_SUCCESS = 'TERM_DATA_SUCCESS';
export const TERM_DATA_FAIL = 'TERM_DATA_FAIL';
export const CREATE_TERM_SUCCESS = 'CREATE_TERM_SUCCESS';
export const CREATE_TERM_FAIL = 'CREATE_TERM_FAIL';
export const EDIT_TERM_SUCCESS = 'EDIT_TERM_SUCCESS';
export const EDIT_TERM_FAIL = 'EDIT_TERM_FAIL';
export const DELETE_TERM_SUCCESS = 'DELETE_TERM_SUCCESS';
export const DELETE_TERM_FAIL = 'DELETE_TERM_FAIL';
export const TERM_DATA_FETCH = 'TERM_DATA_FETCH';

// auth
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const VERIFY_USER_SUCCESS = 'VERIFY_USER_SUCCESS';
export const VERIFY_USER_FAIL = 'VERIFY_USER_FAIL';
export const FORGOT_USER_SUCCESS = 'FORGOT_USER_SUCCESS';
export const FORGOT_USER_FAIL = 'FORGOT_USER_FAIL';
export const RESET_USER_SUCCESS = 'RESET_USER_SUCCESS';
export const RESET_USER_FAIL = 'RESET_USER_FAIL';

// general
export const MODAL_STATUS = 'MODAL_STATUS';
export const SNACKBAR_STATUS = 'SNACKBAR_STATUS';
