export const TERM_DATA_SUCCESS = 'TERM_DATA_SUCCESS';
export const TERM_DATA_FAIL = 'TERM_DATA_FAIL';
export const TERM_DATA_FETCH = 'TERM_DATA_FETCH';

// auth
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const FORGOT_USER_SUCCESS = 'FORGOT_USER_SUCCESS';
export const FORGOT_USER_FAIL = 'FORGOT_USER_FAIL';
export const RESET_USER_SUCCESS = 'RESET_USER_SUCCESS';
export const RESET_USER_FAIL = 'RESET_USER_FAIL';

// general
export const MODAL_STATUS = 'MODAL_STATUS';
