export const TERM_DATA_SUCCESS = 'TERM_DATA_SUCCESS';
export const TERM_DATA_FAIL = 'TERM_DATA_FAIL';
export const TERM_DATA_FETCH = 'TERM_DATA_FETCH';

// auth
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';
